globals: ["@global"]
libs: ["@library"]

view_transitions: true
native_css_nesting: true
inline_css: true
sections: true

title_template: "Chengyu‮ ‬Jin / %s"
og_image: /img/og_emma.png
author: Chengyu‮ ‬Jin
favicon: /img/favicon.png
description: Programmer, Biology student, and Engineer
port: 8083

# OG image
# origin: https://simple-blog.nuejs.org
# og: /img/og.jpg

navigation:
  header:
    - Chengyu Jin: /
    - Contact: /contact/

  footer:
    - © Chengyu Jin: /

    - image: /img/icons/githubline.svg
      url: //github.com/Ovler-Young
      alt: Github Projects
      size: 22 x 22

    - image: /img/icons/github.svg
      url: //github.com/Ovler-Young/website
      alt: Github Repo
      size: 22 x 22

    - image: /img/icons/telegram.svg
      url: //t.me/ChengyuJin
      alt: Telegram
      size: 22 x 22

    - image: /img/icons/linkedin.svg
      url: //www.linkedin.com/in/chengyujin-oliver/
      alt: LinkedIn profile
      size: 22 x 22
